<?xml version="1.0"?>
<!DOCTYPE quiz [
	<!ELEMENT quiz (title, items)>
	<!ELEMENT qtitle (#PCDATA)>
	<!ELEMENT qitems (item)+>	
	<!ELEMENT qitem (question, answer, answer+)>
	<!ELEMENT question (#PCDATA)>
	<!ELEMENT qanswer (#PCDATA)>
	<!ATTLIST qanswer correct (y) #IMPLIED>
]>

<quiz>
  <qtitle>The Quiz</qtitle>
    <qitems>
      <qitem>
        <question>In which continent is the country Japan located?</question>
        <qanswer correct="y">Asia</qanswer>
        <qanswer>Europe</qanswer>
        <qanswer>Africa</qanswer>
        <qanswer>America</qanswer>
      </qitem>
      <qitem>
        <question>Which one cannot swim?</question>
        <qanswer>Tuna</qanswer>
        <qanswer correct="y">Cow</qanswer>
        <qanswer>Whale</qanswer>
        <qanswer>Lobster</qanswer>
      </qitem>		
      <qitem>
        <question>How many points are on a hexagon?</question>
        <qanswer>5</qanswer>
        <qanswer correct="y">6</qanswer>
        <qanswer>7</qanswer>
        <qanswer>8</qanswer>
      </qitem>		
      <qitem>
        <question>World War I began in which year? </question>
        <qanswer>1923</qanswer>
        <qanswer correct="y">1914</qanswer>
        <qanswer>1917</qanswer>
        <qanswer>1938</qanswer>
      </qitem>		
      <qitem>
        <question>World War I began in which year? </question>
        <qanswer>1923</qanswer>
        <qanswer correct="y">1914</qanswer>
        <qanswer>1917</qanswer>
        <qanswer>1938</qanswer>
      </qitem>		
      <qitem>
        <question>Adolf Hitler was born in which country?  </question>
        <qanswer>France</qanswer>       
        <qanswer>Austria</qanswer>
        <qanswer>Hungary</qanswer>
        <qanswer correct="y">Germany</qanswer>
      </qitem>		
       <qitem>
        <question>John F. Kennedy was assassinated in: </question>
        <qanswer>New York</qanswer>
        <qanswer correct="y">Dallas</qanswer>
        <qanswer>Austin</qanswer>
        <qanswer>Miami</qanswer>
      </qitem>		
       <qitem>
        <question>American involvement in the Korean War took place in which decade?   </question>
        <qanswer>1970</qanswer>
        <qanswer correct="y">1950</qanswer>
        <qanswer>1920</qanswer>
        <qanswer>1960</qanswer>
      </qitem>		
       <qitem>
        <question>The disease that ravaged and killed a third of Europe's population in the 14th century is known as:  </question>
        <qanswer>The White Death</qanswer>
        <qanswer correct="y">The Black Plague</qanswer>
        <qanswer>Smallpox</qanswer>
        <qanswer>The Bubonic Plague</qanswer>
      </qitem>		
      <qitem>
        <question>The Hundred Years War was fought between what two countries? </question>
        <qanswer>Italy and Carthage</qanswer>
        <qanswer correct="y">France and England</qanswer>
        <qanswer>England and Germany</qanswer>
        <qanswer>Spain and France</qanswer>
      </qitem>		
       <qitem>
        <question>What nationality of soldiers wear a white kilt? </question>
        <qanswer>France</qanswer>
        <qanswer correct="y">Greek</qanswer>
        <qanswer>Germany</qanswer>
        <qanswer>Britain</qanswer>
      </qitem>		
</quiz>
