<?xml version="1.0"?>
<!DOCTYPE quiz [
	<!ELEMENT quiz (title, items)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT items (item)+>	
	<!ELEMENT item (question, answer, answer+)>
	<!ELEMENT question (#PCDATA)>
	<!ELEMENT answer (#PCDATA)>
	<!ATTLIST answer correct (y) #IMPLIED>
]>

<quiz>
  <title>The Quiz</title>
    <items>
      <item>
        <question>In which continent is the country Japan located?</question>
        <answer correct="y">Asia</answer>
        <answer>Europe</answer>
        <answer>Africa</answer>
        <answer>America</answer>
      </item>
      <item>
        <question>Which one cannot swim?</question>
        <answer>Tuna</answer>
        <answer correct="y">Cow</answer>
        <answer>Whale</answer>
        <answer>Lobster</answer>
      </item>		
      <item>
        <question>How many points are on a hexagon?</question>
        <answer>5</answer>
        <answer correct="y">6</answer>
        <answer>7</answer>
        <answer>8</answer>
      </item>		
    </items>
</quiz>
